### ISSUE TITLE
Dry-run does not work when there are no users

### ISSUE THREAD

**Issue by martbhell** [CSC-IT-Center-for-Science/ansible-role-users#5]
Bug report from UEF:

<pre>
TASK: [ansible-role-users | Add ssh keys to admin users] ********************
failed: [thebe-admin.uef.fi] => (item={'state': 'present', 'shell': u'/bin/bash', 'group': 'csc', 'name': 'cscluis', 'groups':                                                                 u'admin', 'pubkey': 'ssh-rsa AAAAB3NSNIPSNIPw==', 'uid': 5001}) => {"failed": true, "item": {"group": "csc", "groups": "admin", "name": "cscluis", "pubkey                                                                ": "ssh-rsa AAAAB3NzaC1ycSNIPSNIP==", "shell": "/bin/bash", "state": "present", "uid": 5001}}
msg: Failed to lookup user cscluis: 'getpwnam(): name not found: cscluis'
</pre>

**Comment by A1ve5** [comment]
This isn't actually a bug. The playbook will fail because it depends on the created users to proceed. If ran in Dry-run mode, needed users will not be created and the playbook naturally fails.
